### PR TITLE
Version1

### PR DESCRIPTION
**Pull request by viraj02**
Added many features @viraj02  please review the request.
Thanks

### CODE REVIEW

**Comment by IIdeadpool** [comment]
I am unable to create account on Bookmypanditji project....due to firebase issue

**Comment by viraj02** [comment]
Hi deadpool.
Sorry for that.
I have stop the application for some personal reasons.
And have no idea when I will start it.

May I know how you find this project on GitHub.

**Comment by IIdeadpool** [comment]
I downloaded it a month ago and the app was running and I used it as my final year project. I have my project exams after 5 days...can you just start it for the next 5-6 days... Please

**Comment by IIdeadpool** [comment]
Given the circumstance....I used everything from your project itself...and there's no chance I could change now...so please can you help....I would be thankful...stop the application later...

**Comment by viraj02** [comment]
So Sorry to hear that.
But my firebase is now billing.
And I can't afford more firebase bill.
It will just take some time for you to add your own firebase in project.
You can use any thing from my repo except firebase.

**Comment by IIdeadpool** [comment]
Fine....I will try to add my own firebase in the project...but if I can't...can I use yours by paying your bill

**Pull request merged**
